{% set version = "0.32.1" %}

package:
  name: scikit-network
  version: {{ version }}

source:
  # TODO: upstream issue
  # url: https://pypi.io/packages/source/s/scikit-network/scikit-network-{{ version }}.tar.gz
  url: https://github.com/sknetwork-team/scikit-network/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 79566598a430e971ca4e0318d5dcc9c282fae5fefee35f70167417cfdd1370e0

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pytest-runner                          # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp   # [osx]
    - libgomp       # [linux]
    - intel-openmp  # [win]
  host:
    - cython
    - numpy
    - pip
    - pytest-runner
    - python
  run:
    - python
    - scipy >=1.7.3

test:
  source_files:
    - sknetwork/*/tests
    - sknetwork/test_*.py
  imports:
    - sknetwork
  commands:
    - pip check
  requires:
    - coverage
    - pip
    - pytest

about:
  home: https://github.com/sknetwork-team/scikit-network
  summary: Graph algorithms
  license: BSD-3-Clause
  license_file:
    - LICENSE
  doc_url: https://scikit-network.readthedocs.io
  doc_source_url: https://github.com/sknetwork-team/scikit-network/tree/v{{ version }}/docs
  description: |-
    Python package for the analysis of large graphs:
    - Memory-efficient representation of graphs as sparse matrices in scipy format
    - Fast algorithms
    - Simple API inspired by scikit-learn


extra:
  recipe-maintainers:
    - bollwyvl
