{% set version = "0.28.0" %}

package:
  name: scikit-network
  version: {{ version }}

source:
  url: https://github.com/sknetwork-team/scikit-network/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dfb597e0f9c8eefbbc6c4dfc5cdd7ece94926fcc9a166308a2461d76b63375b8
  # TODO: get .pyx into upstream sdist
  # url: https://pypi.io/packages/source/s/scikit-network/scikit-network-{{ version }}.tar.gz
  # sha256: 5fc7d624492af8f3b74681baaacad3bf231d7359480acfceeef7aee7733fd6c0

build:
  entry_points:
    - sknetwork=sknetwork.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp   # [osx]
    - libgomp       # [linux]
    - intel-openmp  # [win]
  host:
    - cython
    - pip
    - python
    - numpy
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy >=1.7.3

test:
  source_files:
    - sknetwork/*/tests
  imports:
    - sknetwork
  commands:
    - pip check
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/sknetwork-team/scikit-network
  summary: Graph algorithms
  license: BSD-3-Clause
  license_file:
    - LICENSE
  doc_url: https://scikit-network.readthedocs.io
  doc_source_url: https://github.com/sknetwork-team/scikit-network/tree/v{{ version }}/docs
  description: |-
    Python package for the analysis of large graphs:
    - Memory-efficient representation of graphs as sparse matrices in scipy format
    - Fast algorithms
    - Simple API inspired by scikit-learn


extra:
  recipe-maintainers:
    - bollwyvl
