{% set version = "0.28.2" %}

package:
  name: scikit-network
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scikit-network/scikit-network-{{ version }}.tar.gz
  sha256: ee890e7ece4534692699639a807d37a56bbf49fc3bec31d34bd3ed594ee951d4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp   # [osx]
    - libgomp       # [linux]
    - intel-openmp  # [win]
  host:
    - cython
    - pip
    - python
    - numpy
  run:
    - {{ pin_compatible('numpy', lower_bound='1.21') }}
    - python
    - scipy

test:
  source_files:
    - sknetwork/*/tests
  imports:
    - sknetwork
  commands:
    - pip check
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/sknetwork-team/scikit-network
  summary: Graph algorithms
  license: BSD-3-Clause
  license_file:
    - LICENSE
  doc_url: https://scikit-network.readthedocs.io
  doc_source_url: https://github.com/sknetwork-team/scikit-network/tree/v{{ version }}/docs
  description: |-
    Python package for the analysis of large graphs:
    - Memory-efficient representation of graphs as sparse matrices in scipy format
    - Fast algorithms
    - Simple API inspired by scikit-learn


extra:
  recipe-maintainers:
    - bollwyvl
