# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.33.3

package:
  name: scikit-network
  version: ${{ version }}

source:
  # TODO: upstream issue
  # url: https://pypi.io/packages/source/s/scikit-network/scikit-network-{{ version }}.tar.gz
  url: https://github.com/sknetwork-team/scikit-network/archive/refs/tags/v${{ version }}.tar.gz
  sha256: de16b1cf30cb113f7324e877a044d49f68f06beeda16fc3e448728a0e8783e8e

build:
  number: 1
  skip: match(python, "<3.8")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - cython
        - numpy
        - pytest-runner
        - python
    - if: osx
      then: llvm-openmp
    - if: linux
      then: libgomp
    - if: win
      then: intel-openmp
  host:
    - cython <=3.0.12
    - numpy
    - pip
    - pytest-runner
    - python
    - scipy
    - setuptools
  run:
    - python
    - scipy >=1.7.3

tests:
  - python:
      imports: sknetwork
  - files:
      recipe:
        - run_test.py
      source:
        - sknetwork/*/tests/
        - sknetwork/test_*.py
    requirements:
      run:
        - coverage
        - pytest
    script:
      - python run_test.py

about:
  summary: Graph algorithms
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/sknetwork-team/scikit-network
  documentation: https://scikit-network.readthedocs.io
  description: |-
    Python package for the analysis of large graphs:
    - Memory-efficient representation of graphs as sparse matrices in scipy format
    - Fast algorithms
    - Simple API inspired by scikit-learn

extra:
  recipe-maintainers:
    - bollwyvl
